spring:

  datasource:
    url: jdbc:sqlserver://Note-Ricardo\SQLEXPRESS:1433;databaseName=treinamentos;encrypt=false
    username: sa
    password: rik20190

  jpa:
    hibernate:
      ddl-auto: validate

    show-sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true

server:
  port: 8080

storage:
  local:
    path: C:/Temp/UploadsC7Flex

google:
  client-id: 783484822731-8jon381ark5m43f9o0r450rhblilhqj6.apps.googleusercontent.com

jwt:
  secret: 8f3dfb4c4d9a84b92a43d8b0df1f2ef74ab11b5caa8d6d0db54bb56d2e9b4d75
  expiration: 86400000